# Generated by Django 3.1.6 on 2021-02-21 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examname', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicname', models.CharField(max_length=150, null=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainApp.categories')),
                ('exams', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainApp.exams')),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoruGorseli', models.ImageField(upload_to='sorugorseliuploads/')),
                ('SoruMetni', models.TextField()),
                ('A', models.CharField(max_length=250)),
                ('B', models.CharField(max_length=250)),
                ('C', models.CharField(max_length=250)),
                ('D', models.CharField(max_length=250)),
                ('E', models.CharField(max_length=250)),
                ('IdealCozumSuresi', models.SmallIntegerField()),
                ('DogruCevap', models.CharField(max_length=250)),
                ('CozumGorseli', models.ImageField(upload_to='cozumgorseliuploads/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainApp.categories')),
                ('exams', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainApp.exams')),
                ('topics', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainApp.topics')),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='exams',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainApp.exams'),
        ),
    ]
