# Generated by Django 3.1.6 on 2021-02-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='ders',
            field=models.CharField(max_length=100, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='exams',
            name='examname',
            field=models.CharField(max_length=100, verbose_name='Sınav Adı'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topicname',
            field=models.CharField(max_length=150, null=True, verbose_name='Ders Başlığı Adı'),
        ),
    ]
