# Generated by Django 3.1.6 on 2021-02-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20210222_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(default='categoriesuploads/defaultphoto.jpg', null=True, upload_to='categoriesuploads/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='CozumGorseli',
            field=models.ImageField(null=True, upload_to='questions-cozumuploads/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='SoruGorseli',
            field=models.ImageField(null=True, upload_to='questions-soruuploads/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='image',
            field=models.ImageField(null=True, upload_to='topicsuploads/%Y/%m/%d'),
        ),
    ]
