# Generated by Django 3.1.4 on 2021-02-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20210222_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='authorId',
            field=models.IntegerField(null=True),
        ),
    ]
