# Generated by Django 3.1.4 on 2021-03-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardTitle', models.CharField(max_length=50)),
                ('CardAuthor', models.CharField(max_length=50)),
                ('CardAuthorId', models.IntegerField()),
                ('CardCreateDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
