# Generated by Django 3.1.4 on 2021-03-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_userscard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersCard',
        ),
    ]
