# Generated by Django 3.1.4 on 2021-03-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='BlogTags',
            field=models.ManyToManyField(blank=True, to='mainApp.Tags'),
        ),
    ]
