# Generated by Django 3.1.4 on 2021-03-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_auto_20210309_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='BlogTags',
        ),
        migrations.AddField(
            model_name='blog',
            name='BlogTagId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
