# Generated by Django 3.1.4 on 2021-03-10 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_auto_20210310_1801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
