# Generated by Django 3.1.4 on 2021-03-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_blog_blogmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
