# Generated by Django 3.1.4 on 2021-03-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_auto_20210310_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='tagid',
            field=models.IntegerField(null=True),
        ),
    ]
