# Generated by Django 3.1.4 on 2021-03-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0022_auto_20210311_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='tagid',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='tagid',
            field=models.ManyToManyField(blank=True, to='mainApp.Tags'),
        ),
    ]
