# Generated by Django 3.1.4 on 2021-03-11 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0025_auto_20210311_1311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogModel',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
