# Generated by Django 3.1.4 on 2021-03-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0026_auto_20210311_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlogTitle', models.CharField(max_length=60)),
                ('BlogContent', models.TextField()),
                ('BlogCreatedDate', models.DateTimeField(auto_now_add=True)),
                ('BlogAuthor', models.CharField(max_length=60, null=True)),
                ('BlogAuthorId', models.IntegerField(null=True)),
                ('CategoryId', models.IntegerField(null=True)),
            ],
        ),
    ]
