# Generated by Django 3.1.4 on 2021-03-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0027_blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='BlogModel',
        ),
    ]
