# Generated by Django 3.1.4 on 2021-03-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0028_auto_20210311_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=30, null=True)),
                ('CategoryAuthor', models.CharField(max_length=30, null=True)),
                ('CategoryAuthorId', models.IntegerField(null=True)),
                ('CategoryCreatedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
