# Generated by Django 3.1.4 on 2021-03-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0029_categorymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='CategoryName',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
